# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lmaitland/Documents/Projects/mvc++/mvcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lmaitland/Documents/Projects/mvc++/mvcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lmaitland/Documents/Projects/mvc++/mvcpp/CMakeFiles /home/lmaitland/Documents/Projects/mvc++/mvcpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lmaitland/Documents/Projects/mvc++/mvcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mvcpp

# Build rule for target.
mvcpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mvcpp
.PHONY : mvcpp

# fast build rule for target.
mvcpp/fast:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/build
.PHONY : mvcpp/fast

#=============================================================================
# Target rules for targets named Request

# Build rule for target.
Request: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Request
.PHONY : Request

# fast build rule for target.
Request/fast:
	$(MAKE) -f benchmarking/CMakeFiles/Request.dir/build.make benchmarking/CMakeFiles/Request.dir/build
.PHONY : Request/fast

#=============================================================================
# Target rules for targets named Route

# Build rule for target.
Route: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Route
.PHONY : Route

# fast build rule for target.
Route/fast:
	$(MAKE) -f benchmarking/CMakeFiles/Route.dir/build.make benchmarking/CMakeFiles/Route.dir/build
.PHONY : Route/fast

#=============================================================================
# Target rules for targets named FileServer

# Build rule for target.
FileServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileServer
.PHONY : FileServer

# fast build rule for target.
FileServer/fast:
	$(MAKE) -f examples/CMakeFiles/FileServer.dir/build.make examples/CMakeFiles/FileServer.dir/build
.PHONY : FileServer/fast

#=============================================================================
# Target rules for targets named Router

# Build rule for target.
Router: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Router
.PHONY : Router

# fast build rule for target.
Router/fast:
	$(MAKE) -f examples/CMakeFiles/Router.dir/build.make examples/CMakeFiles/Router.dir/build
.PHONY : Router/fast

source/Exception/Exception.o: source/Exception/Exception.cpp.o
.PHONY : source/Exception/Exception.o

# target to build an object file
source/Exception/Exception.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Exception/Exception.cpp.o
.PHONY : source/Exception/Exception.cpp.o

source/Exception/Exception.i: source/Exception/Exception.cpp.i
.PHONY : source/Exception/Exception.i

# target to preprocess a source file
source/Exception/Exception.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Exception/Exception.cpp.i
.PHONY : source/Exception/Exception.cpp.i

source/Exception/Exception.s: source/Exception/Exception.cpp.s
.PHONY : source/Exception/Exception.s

# target to generate assembly for a file
source/Exception/Exception.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Exception/Exception.cpp.s
.PHONY : source/Exception/Exception.cpp.s

source/Exception/HttpException.o: source/Exception/HttpException.cpp.o
.PHONY : source/Exception/HttpException.o

# target to build an object file
source/Exception/HttpException.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Exception/HttpException.cpp.o
.PHONY : source/Exception/HttpException.cpp.o

source/Exception/HttpException.i: source/Exception/HttpException.cpp.i
.PHONY : source/Exception/HttpException.i

# target to preprocess a source file
source/Exception/HttpException.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Exception/HttpException.cpp.i
.PHONY : source/Exception/HttpException.cpp.i

source/Exception/HttpException.s: source/Exception/HttpException.cpp.s
.PHONY : source/Exception/HttpException.s

# target to generate assembly for a file
source/Exception/HttpException.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Exception/HttpException.cpp.s
.PHONY : source/Exception/HttpException.cpp.s

source/Http/Query.o: source/Http/Query.cpp.o
.PHONY : source/Http/Query.o

# target to build an object file
source/Http/Query.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Query.cpp.o
.PHONY : source/Http/Query.cpp.o

source/Http/Query.i: source/Http/Query.cpp.i
.PHONY : source/Http/Query.i

# target to preprocess a source file
source/Http/Query.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Query.cpp.i
.PHONY : source/Http/Query.cpp.i

source/Http/Query.s: source/Http/Query.cpp.s
.PHONY : source/Http/Query.s

# target to generate assembly for a file
source/Http/Query.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Query.cpp.s
.PHONY : source/Http/Query.cpp.s

source/Http/Request.o: source/Http/Request.cpp.o
.PHONY : source/Http/Request.o

# target to build an object file
source/Http/Request.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Request.cpp.o
.PHONY : source/Http/Request.cpp.o

source/Http/Request.i: source/Http/Request.cpp.i
.PHONY : source/Http/Request.i

# target to preprocess a source file
source/Http/Request.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Request.cpp.i
.PHONY : source/Http/Request.cpp.i

source/Http/Request.s: source/Http/Request.cpp.s
.PHONY : source/Http/Request.s

# target to generate assembly for a file
source/Http/Request.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Request.cpp.s
.PHONY : source/Http/Request.cpp.s

source/Http/Response.o: source/Http/Response.cpp.o
.PHONY : source/Http/Response.o

# target to build an object file
source/Http/Response.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Response.cpp.o
.PHONY : source/Http/Response.cpp.o

source/Http/Response.i: source/Http/Response.cpp.i
.PHONY : source/Http/Response.i

# target to preprocess a source file
source/Http/Response.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Response.cpp.i
.PHONY : source/Http/Response.cpp.i

source/Http/Response.s: source/Http/Response.cpp.s
.PHONY : source/Http/Response.s

# target to generate assembly for a file
source/Http/Response.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Response.cpp.s
.PHONY : source/Http/Response.cpp.s

source/Http/Server.o: source/Http/Server.cpp.o
.PHONY : source/Http/Server.o

# target to build an object file
source/Http/Server.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Server.cpp.o
.PHONY : source/Http/Server.cpp.o

source/Http/Server.i: source/Http/Server.cpp.i
.PHONY : source/Http/Server.i

# target to preprocess a source file
source/Http/Server.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Server.cpp.i
.PHONY : source/Http/Server.cpp.i

source/Http/Server.s: source/Http/Server.cpp.s
.PHONY : source/Http/Server.s

# target to generate assembly for a file
source/Http/Server.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Http/Server.cpp.s
.PHONY : source/Http/Server.cpp.s

source/Log/Log.o: source/Log/Log.cpp.o
.PHONY : source/Log/Log.o

# target to build an object file
source/Log/Log.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Log/Log.cpp.o
.PHONY : source/Log/Log.cpp.o

source/Log/Log.i: source/Log/Log.cpp.i
.PHONY : source/Log/Log.i

# target to preprocess a source file
source/Log/Log.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Log/Log.cpp.i
.PHONY : source/Log/Log.cpp.i

source/Log/Log.s: source/Log/Log.cpp.s
.PHONY : source/Log/Log.s

# target to generate assembly for a file
source/Log/Log.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Log/Log.cpp.s
.PHONY : source/Log/Log.cpp.s

source/Routing/Route.o: source/Routing/Route.cpp.o
.PHONY : source/Routing/Route.o

# target to build an object file
source/Routing/Route.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Routing/Route.cpp.o
.PHONY : source/Routing/Route.cpp.o

source/Routing/Route.i: source/Routing/Route.cpp.i
.PHONY : source/Routing/Route.i

# target to preprocess a source file
source/Routing/Route.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Routing/Route.cpp.i
.PHONY : source/Routing/Route.cpp.i

source/Routing/Route.s: source/Routing/Route.cpp.s
.PHONY : source/Routing/Route.s

# target to generate assembly for a file
source/Routing/Route.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Routing/Route.cpp.s
.PHONY : source/Routing/Route.cpp.s

source/Routing/Router.o: source/Routing/Router.cpp.o
.PHONY : source/Routing/Router.o

# target to build an object file
source/Routing/Router.cpp.o:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Routing/Router.cpp.o
.PHONY : source/Routing/Router.cpp.o

source/Routing/Router.i: source/Routing/Router.cpp.i
.PHONY : source/Routing/Router.i

# target to preprocess a source file
source/Routing/Router.cpp.i:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Routing/Router.cpp.i
.PHONY : source/Routing/Router.cpp.i

source/Routing/Router.s: source/Routing/Router.cpp.s
.PHONY : source/Routing/Router.s

# target to generate assembly for a file
source/Routing/Router.cpp.s:
	$(MAKE) -f CMakeFiles/mvcpp.dir/build.make CMakeFiles/mvcpp.dir/source/Routing/Router.cpp.s
.PHONY : source/Routing/Router.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mvcpp"
	@echo "... Route"
	@echo "... Request"
	@echo "... Router"
	@echo "... FileServer"
	@echo "... source/Exception/Exception.o"
	@echo "... source/Exception/Exception.i"
	@echo "... source/Exception/Exception.s"
	@echo "... source/Exception/HttpException.o"
	@echo "... source/Exception/HttpException.i"
	@echo "... source/Exception/HttpException.s"
	@echo "... source/Http/Query.o"
	@echo "... source/Http/Query.i"
	@echo "... source/Http/Query.s"
	@echo "... source/Http/Request.o"
	@echo "... source/Http/Request.i"
	@echo "... source/Http/Request.s"
	@echo "... source/Http/Response.o"
	@echo "... source/Http/Response.i"
	@echo "... source/Http/Response.s"
	@echo "... source/Http/Server.o"
	@echo "... source/Http/Server.i"
	@echo "... source/Http/Server.s"
	@echo "... source/Log/Log.o"
	@echo "... source/Log/Log.i"
	@echo "... source/Log/Log.s"
	@echo "... source/Routing/Route.o"
	@echo "... source/Routing/Route.i"
	@echo "... source/Routing/Route.s"
	@echo "... source/Routing/Router.o"
	@echo "... source/Routing/Router.i"
	@echo "... source/Routing/Router.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

