BUILD_NAME = route
SOURCES    = Http/Request.cpp Http/Query.cpp Exception/HttpException.cpp Exception/Exception.cpp Routing/Route.cpp Routing/Router.cpp Http/Response.cpp Log/Log.cpp

include ../Makefile.inc